import type { Metadata } from "next"; 
import localFont from "next/font/local"; 
import "./globals.css"; 
import NavBars from './component/navbar'; 

// นำเข้า type Metadata จาก Next.js เพื่อใช้กำหนด metadata ของแอปพลิเคชัน
// นำเข้า localFont จาก "next/font/local" เพื่อจัดการฟอนต์ท้องถิ่น
// นำเข้าไฟล์ CSS ทั่วไป (globals.css) ที่ใช้สำหรับสไตล์ในทุกหน้า
// นำเข้า component "NavBars" สำหรับใช้ใน Layout

const geistSans = localFont({
  src: "./fonts/GeistVF.woff", // ระบุที่มาของไฟล์ฟอนต์ (Geist Sans)
  variable: "--font-geist-sans", // ชื่อของ CSS Variable ที่จะสร้างขึ้นสำหรับฟอนต์นี้
  weight: "100 900", // กำหนดน้ำหนักของฟอนต์ ตั้งแต่ 100 ถึง 900
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff", // ระบุที่มาของไฟล์ฟอนต์ (Geist Mono)
  variable: "--font-geist-mono", // ชื่อของ CSS Variable ที่จะสร้างขึ้นสำหรับฟอนต์นี้
  weight: "100 900", // กำหนดน้ำหนักของฟอนต์ ตั้งแต่ 100 ถึง 900
});

// กำหนด metadata สำหรับหน้าเว็บ เช่น ชื่อเว็บและคำอธิบาย
export const metadata: Metadata = {
  title: "Create Next App", // ชื่อของแอป
  description: "Generated by create next app", // คำอธิบายของแอป
};

// ฟังก์ชัน RootLayout เป็นฟังก์ชันหลักที่ใช้ในการกำหนด Layout ของหน้าเว็บทั้งหมด
// โดยจะรับค่า children ซึ่งเป็นเนื้อหาของแต่ละหน้า
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode; // ประกาศ children เป็น React Node (เนื้อหาภายในหน้า)
}>) {
  return (
    <html lang="en"> 
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      > 
        {/* กำหนดฟอนต์ด้วย CSS Variables และเปิดใช้งาน antialiasing */}
        {/* แสดง NavBars ซึ่งเป็นเมนูนำทาง */}
        <NavBars />
        {children} {/* แสดงเนื้อหาของแต่ละหน้า */}
      </body>
    </html>
  );
}
